"""add_hf_base_models_column_v4

Revision ID: 0fca875aa9e8
Revises: 8a6d489340fe
Create Date: <YYYY-MM-DD HH:MM:SS.ffffff> # Alembic 会自动填充创建日期

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0fca875aa9e8'
down_revision: Union[str, None] = '8a6d489340fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hf_models",
        sa.Column("hf_base_models", postgresql.JSONB(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hf_models", "hf_base_models")
    # ### end Alembic commands ###
