'''add_hf_readme_tasks_to_hf_models

Revision ID: b2c8f1a90d3e
Revises: add_hf_base_models_to_hf_models
Create Date: 2024-05-16 10:00:00.000000

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b2c8f1a90d3e'
down_revision: Union[str, None] = '0fca875aa9e8' # 指向新生成的 add_hf_base_models 脚本
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hf_models', sa.Column('hf_readme_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hf_models', 'hf_readme_tasks')
    # ### end Alembic commands ### 