# ruff.toml

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# Enable Pyflakes `E` and `F` codes by default.
# Enable a subset of the pycodestyle `E` and `W` codes by default.
# Enable the isort `I` rules.
# Enable the pydocstyle `D` rules.
# Enable the flake8-bugbear `B` rules.
# Enable Ruff-specific rules `RUF`
select = ["E", "F", "W", "I", "D", "B", "RUF"]
ignore = [
    "E501", # Line too long, handled by formatter
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D107", # Missing docstring in __init__
]

# Allow unused variables in `__init__.py`.
[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.pydocstyle]
convention = "google" # Or numpy, pep257

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto" 