name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # Required for conda activation

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11' # Match the version in environment.yml
        environment-file: environment.yml
        activate-environment: AIGraphX # Name of the conda environment

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --prune
        pip install -e . # Install project in editable mode if setup.py exists

    - name: Lint with Ruff
      run: ruff check .

    - name: Check formatting with Ruff
      run: |
        ruff format --check .

    - name: Type check with MyPy
      run: mypy aigraphx tests

    - name: Test with Pytest
      run: pytest 